<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Jellyfin.Models\Jellyfin.Models.csproj" />
	</ItemGroup>

</Project>
