<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Jellyfin.Sdk" Version="2025.10.21" />
		<PackageReference Include="Microsoft.Kiota.Abstractions" Version="2.0.0" />
	</ItemGroup>

</Project>
