name: Build and Tests

on:  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  build:    
    runs-on: windows-2022
    
    steps:      
      - uses: actions/checkout@v4.1.1
      
      

      - name: branch
        run: |
          echo ${{ github.ref }}
      - name: test
        if: ${{ github.ref == 'refs/head/master' }}
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Jellyfin UWP
          path: Jellyfin UWP\\AppPackages
